config/routes.rb
Rails.application.routes.draw do
  resources :categories_transaction1s
  resources :transactions1s
  resources :categories
  authenticated :user do
    root to: 'categories#index'
  end
  unauthenticated :user do
    root to: "splashs#index", as: :unauthenticated_root
  end
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user, class_name: 'User', foreign_key: :user_id
  has_many :category_transactions1s, dependent: :delete_all
  has_many :transactions1s, through: :category_transactions1s
  validates :name, presence: true
  def amount
    0
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_category, only: %i[show edit update destroy]

  # GET /categories
  def index
    @categories = Category.where(user: current_user)
  end

  # GET /categories/1
  def show
    @transactions1s = @category.transactions1s
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)
    @category.user = current_user
    respond_to do |format|
      if @category.save
        format.html { redirect_to categories_url, notice: 'Category was successfully created.' }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_category
    @category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:name, :icon)
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_category.html.erb
<div id="<%= dom_id category %>">
  <p>
    <strong>Name:</strong>
    <%= category.name %>
  </p>

  <p>
    <strong>Icon:</strong>
    <%= category.icon %>
  </p>

  <p>
    <strong>User:</strong>
    <%= category.User_id %>
  </p>

</div>

app/views/categories/_form.html.erb
<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>
<%= form_with(model: category) do |form| %>
  <section class="container">
  <div class="d-flex flex-column align-items-center">
 <div class= "d-flex flex-column align-items-center w-75 mb-3">
      <%= form.text_field :name, class: "form-control w-75 mb-3 ", placeholder: "Name" %>
   

  
      <%= form.text_field :icon, class: "form-control w-75 mb-3", placeholder: "Icon" %>
    
  </section>

  <div class="bottom-container position-fixed bottom-0 w-100 btn-bg">
    <div class="inner-bottom-container text-center">
      <%= form.submit "ADD CATEGORY", class: "bottom-btn text-white border w-90 btn-bg" %>
    </div>
    </div>
    </div>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to "Show this category", @category %> |
  <%= link_to "Back to categories", categories_path %>
</div>

app/views/categories/index.html.erb
<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>
<section class="container">
  <% if @categories.blank?%>
    <p>You don't have any category yet! Click below to add one.</p>
  <% else %>
    <% @categories.each do |category| %>
      <%= link_to category_path(category.id) do %>
  <article class="row d-flex border my-1">
    <div class="col-3">
      <img src=<%= category.icon %> alt="Category Icon" class="m-1 img-fluid rounded-1">
    </div>
    <div class="col-6 pt-3">
      <p class="category-name"><%= category.name %></p>
      <span class="date"><%= category.created_at %></span>
    </div>
    
  </article>
<% end %>
    <% end %>
  <% end %>
</section>
<div class="bottom-container position-fixed bottom-0 w-100">
  <div class="inner-bottom-container text-center">
    <%= link_to "NEW CATEGORY", new_category_path, class: "bottom-btn" %>
  </div>
</div>

app/views/categories/new.html.erb
<h1 class="text-center">New category</h1>

<%= render "form", category: @category %>

<br>

<div class="text-center">
  <%= link_to "Back to categories", categories_path %>
</div>

app/views/categories/show.html.erb
<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>
<section class="container">
  <%= link_to category_path(@category.id) do %>
  <article class="row d-flex border my-1">
    <div class="col-3">
      <img src=<%= @category.icon %> alt="Category Icon" class="m-1 img-fluid rounded-1">
    </div>
    <div class="col-6 pt-3">
      <p class="category-name"><%= @category.name %></p>
      <span class="date"><%= @category.created_at %></span>
    </div>
    <div class="col-3 pt-3">
      <span class="amount-dls">$<%= @category.amount %></span>
    </div>
  </article>
<% end %>
  <br>
  <% @transactions1s.each do |transac| %>
    <article class="row border my-1">
  <div class="col-9">
    <p class="transac-name">Transaction <%= transac.name %></p>
    <p class="date"><%= transac.created_at %></p>
  </div>
  <div class="col-3">
    <span class="amount-dls">$<%= transac.amount %></span>
  </div>
</article>
  <% end %>
</section>

<div class="bottom-container position-fixed bottom-0 w-100">
  <div class="inner-bottom-container text-center">
    <%= link_to "NEW TRANSACTION", new_transactions1_path, class: "bottom-btn" %>
  </div>
</div>